language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
script:
  - "npm test"
  - if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then npm run test-saucelabs; fi
env:
  global:
    - secure: >-
        jsB1K0BDWAVhn6B3zhztiK4kY54NXCag/18fwJLoJbMalp8pcTAfRuCaUBgiBkhUFgG6wmIbjDYEMMvBGigyLTzXYh207G/ZK97BJ95jhlAFZBRTfzfs36p4PcpSnsIqxt8DJ8xFCh1r0HUbsh+UNWCmpuW/lLnZCt/ONqS8XBQVd8F2xEVpGC4T+6IDByk6TzVclJuPGubuAfodXGHMmIhAENPGDssYogQLnvJ2tC7QFFhTeDw7UeRHlYr0KoVY6mzHodwmSh2IIPWrf5FMapECOnAu+7DMtxhfJvUFOVhPzVoVsMn/56BLx7I4ans+HWK9gH++D7EccXfTqAzOFEPcVMBbyCLl2CmpxF/QvMD6z1kNJZ25mJhLpYlU1A+5BfYmcFmgVeBX46rFro4XtxRk+SXUqVJTGau7yyEhWMN4ATExIrDLYmEZ74FcSl5nDteSoM6NWASR2VOkXkq0XAPd7/r2SykP+lsypHmIEM4J4l89zzZdNhTDYTOfKetBymEaZCEwNCEezWsNhtv7F5O3biMATepq+uuRPuIH3M8qYJssiHab8yYK4WL+das/BEeBHWhp/kBfJWANy6XEk/HrtalxdclY1IjCtJPZUyf4TrpqmP955WZFQIxj/6tHRU7MLdi0EzRUi37VLfpsAECZgI96pBXNdZxaz/yU0fY=
    - secure: >-
        IyzM7W5xo8oWuDTbc2TQh4fMqlqXDKWqUG0pQXO8VbRRtYDRR5nqaqJzETR7UyYd9+I0ij+/4XBdEQ94VlpKVki5NfqaNfZkwXEoDF3vKqAmFDBsijmkJ03E4y2bAdtfaQBV9CWpeQmGGDw5PHcsUh9rRZYdupuqizml7LiFpbocxfcpOM+nj639jchg24Yi90Sfw7k5IMbIYmTUDBvxOIJNjKiy7+xOT+dQFAeFJfneaSHIlV/W/Vh5kOOC6S1RrivbeUY60z81cqHLke3R4xO1+kg/F3djpSm2EopcJYsl+HtQZex1FwixQx052yAlBAkIL75gR/NB89EjygYEFDH2zm8vLE4+ZY3AMcEmjNHPEDG9hSsJjwFgfYKckcm1kAy78NzuBbh5AsB58hTS44qzeCs09KHbYasrdps27v7PvwvY+f9VqQ/LFGXuvZPDtnVvj7/WAW8B42VqpTBumuOW57et+im+viEPQoHkRBvG6kk+xtvd+WCDXDiShXGIoTHKSjlZ5B973dH7BGAUkdAi4mvY6s5MEqhFdiiTSqfuTuVsn3xIZtEqHs5+ij+a/8fa8MLPZG2+RFdqx6h+EDKZ7qlkrTwcVFccDEl9A2CwvJWdaaW6Hb8cqW2SCPUibgJ6IIYIbIH2TT8l5xLnt041JCPK52flgk3+QlV4w6A=
